### PR TITLE
Adds jest unit tests

### PR DESCRIPTION
**Pull request by cesaragv**
This PR sets up and adds the initial unit tests for the front-end. 
As more files are touched during the run `npm test`, code coverage decreases

Screen Shot 2020-04-28 at 11 16 50 PM

### CODE REVIEW

**Comment by reddigari** [comment]
Looks great! I've never used snapshots to test against...how likely is it that they will need to be changed as we keep developing? I have a feeling they will be very useful vs manually writing assertions since we're strapped for time.

**Comment by cesaragv** [comment]
> Looks great! I've never used snapshots to test against...how likely is it that they will need to be changed as we keep developing? I have a feeling they will be very useful vs manually writing assertions since we're strapped for time.

@reddigari I used them before, and once the project is stable, they don't really need to change much.

**Comment by reddigari** [comment]
Reminder to add the execution of these tests to the Github Actions config once #75 is merged.

**Comment by reddigari** [comment]
Oh I didn't catch that --- yeah it's good practice to leave them in because it ensures everyone's using the same versions and prevents dependency hell when people clone and install. @cesaragv could we put it back and see if we have the version issues you mentioned?

**Comment by cesaragv** [comment]
> Oh I didn't catch that --- yeah it's good practice to leave them in because it ensures everyone's using the same versions and prevents dependency hell when people clone and install. @cesaragv could we put it back and see if we have the version issues you mentioned?

@reddigari yes, I just did

**Pull request merged**
